"""first

Revision ID: a6c75c8b2aa9
Revises: 
Create Date: 2020-12-06 12:38:34.060471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6c75c8b2aa9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('supervisor_fname', sa.String(length=64), nullable=False),
    sa.Column('supervisor_lname', sa.String(length=64), nullable=False),
    sa.Column('crew_id', sa.Integer(), nullable=False),
    sa.Column('date_of_incident', sa.DateTime(), nullable=False),
    sa.Column('scale_of_cleanup', sa.String(length=64), nullable=False),
    sa.Column('type_of_building', sa.String(length=64), nullable=False),
    sa.Column('street_address', sa.String(length=256), nullable=False),
    sa.Column('zipcode', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=256), nullable=False),
    sa.Column('cross_street', sa.String(length=256), nullable=True),
    sa.Column('moniker', sa.String(length=64), nullable=True),
    sa.Column('gps_lat', sa.Float(precision=2), nullable=False),
    sa.Column('gps_lng', sa.Float(precision=2), nullable=False),
    sa.Column('notes', sa.String(length=256), nullable=True),
    sa.Column('investigation_status', sa.String(length=64), nullable=True),
    sa.Column('is_hotspot', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('pwd_hash', sa.String(length=128), nullable=True),
    sa.Column('urole', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('report__image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=128), nullable=False),
    sa.Column('filename', sa.String(length=128), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suspect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('gang', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suspect__image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=128), nullable=False),
    sa.Column('filename', sa.String(length=128), nullable=False),
    sa.Column('suspect_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['suspect_id'], ['suspect.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suspect__image')
    op.drop_table('suspect')
    op.drop_table('report__image')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('report')
    # ### end Alembic commands ###
