"""first

Revision ID: d0514e3715e2
Revises: 
Create Date: 2020-11-10 13:22:55.097296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0514e3715e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('pwd_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspectors_email'), 'inspectors', ['email'], unique=True)
    op.create_table('reporters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('pwd_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reporters_email'), 'reporters', ['email'], unique=True)
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supervisor_fname', sa.String(length=64), nullable=False),
    sa.Column('supervisor_lname', sa.String(length=64), nullable=False),
    sa.Column('crew_id', sa.Integer(), nullable=True),
    sa.Column('date_of_incident', sa.DateTime(), nullable=False),
    sa.Column('type_of_building', sa.String(length=64), nullable=True),
    sa.Column('street_address', sa.String(length=256), nullable=True),
    sa.Column('zipcode', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=256), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['reporters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report')
    op.drop_index(op.f('ix_reporters_email'), table_name='reporters')
    op.drop_table('reporters')
    op.drop_index(op.f('ix_inspectors_email'), table_name='inspectors')
    op.drop_table('inspectors')
    # ### end Alembic commands ###
